name: Deploy Frontend to Main Domain

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Lấy mã nguồn mới nhất
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: 🏗️ Cài đặt và Build React
        working-directory: ./frontend
        run: |
          npm install
          CI=false npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_MEDIA_BASE_URL: ${{ secrets.VITE_MEDIA_BASE_URL }}

      - name: 🚀 Deploy trực tiếp vào private_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_MAIN_USER }} 
          password: ${{ secrets.FTP_MAIN_PASS }} 
          local-dir: ./frontend/dist/ 
          
          # THAY ĐỔI Ở ĐÂY: Trỏ thẳng vào private_html
          # Nếu tài khoản FTP đang ở trong public_html, ta dùng ../ để nhảy ra ngoài rồi vào private
          server-dir: ../private_html/ 
          
          protocol: ftp
          port: 21