name: Deploy Node.js Backend

on:
  push:
    branches:
      - main # Chú ý: Nếu nhánh hiện tại của bạn tên là 'master', hãy đổi chữ 'main' thành 'master' nhé

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn mới nhất
        uses: actions/checkout@v4

      - name: Deploy code lên hosting Mắt Bão qua FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          dangerous-clean-slate: false # Giữ an toàn, không xóa nhầm file trên hosting