name: Deploy React Admin

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-admin/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn mới nhất
        uses: actions/checkout@v4

      - name: Cài đặt Node.js môi trường bản mới nhất (Node 20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cài đặt thư viện và Build (Đóng gói)
        working-directory: ./frontend-admin
        run: |
          npm install
          CI=false npm run build

      - name: Deploy gói Build lên hosting Mắt Bão
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_ADMIN_USER }} # <--- Đã đổi sang chìa khóa mới của Client
          password: ${{ secrets.FTP_ADMIN_PASS }} # <--- Đã đổi sang mật khẩu mới của Client
          local-dir: ./frontend-admin/dist/ 
          
          # Đã XÓA dòng server-dir vì tài khoản FTP mới trỏ thẳng vào đích rồi
          
          protocol: ftp
          dangerous-clean-slate: false