name: Deploy React to Main Domain

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Lấy mã nguồn mới nhất
        uses: actions/checkout@v4

      - name: 🟢 Cài đặt Node.js (Bản 22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 🏗️ Cài đặt và Build React
        working-directory: ./frontend
        run: |
          npm install
          CI=false npm run build


      - name: 🚀 Deploy chuẩn vào tên miền chính
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }} 
          
          local-dir: ./frontend/dist/ 
          
          # QUAN TRỌNG: Chỉ dùng dấu chấm vì tài khoản FTP đã trỏ đúng thư mục rồi
          server-dir: ./ 
          
          protocol: ftp
          port: 21
          timeout: 900000 
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose